### ISSUE TITLE
Fix template YAML files

### ISSUE THREAD

**Issue by patrikbraborec** [emitbase/emitbase-core#3]
The current template file for thresholds look as follow:

```yaml
first_threshold:
  expression: ''
  cron: ''
```

For notifications as follow:

```yaml
first_notification:
  email:
    reciever: ''
    message: ''
```

The problem is in difference between `first_threshold`, and `first_notification`. The keys must be the same.
